export const illustrations = {
  wheelchairRamp: require("../assets/illustrations/features/wheelchair_ramp_v2.png"),
  extraBoardingTime: require("../assets/illustrations/features/extra_boarding_time_v2.png"),
  audioIdentification: require("../assets/illustrations/features/audio_identification_v2.png"),
  physicalHelpButton: require("../assets/illustrations/physical_help_button_v4.png"),
  nearestStopLoading: require("../assets/illustrations/nearest_stop_loading_v1.png"),
  journeyFindBus: require("../assets/illustrations/journey_find_bus_v2.png"),
  chooseBus: require("../assets/illustrations/choose_bus_v1.png"),
  journeyReview: require("../assets/illustrations/journey_review_v1.png"),
  onboardGuidance: require("../assets/illustrations/onboard_guidance_v1.png"),
  assistCommunication: require("../assets/illustrations/assist_communication_v2.png"),
  accessibilityProfile: require("../assets/illustrations/accessibility_profile_v2.png"),
  journeyGuide: {
    walkingToStop: require("../assets/illustrations/journey-guide/walking_to_stop_v2.png"),
    waitingForBus: require("../assets/illustrations/journey-guide/waiting_for_bus_v2.png"),
    safeBoarding: require("../assets/illustrations/journey-guide/safe_boarding_v2.png"),
    onboardJourney: require("../assets/illustrations/journey-guide/onboard_journey_v2.png"),
    safeAlighting: require("../assets/illustrations/journey-guide/safe_alighting_v2.png"),
    journeyComplete: require("../assets/illustrations/journey-guide/journey_complete_v2.png"),
  },
} as const;
