import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation, PresentationFile, FileBlob} from '@oai/artifact-tool';
const root='C:/Users/simho/Downloads/BusTech/GoAssist';
const tmp=path.join(root,'artifacts/project-draft/slides/vl53l0x-update');
await fs.mkdir(tmp,{recursive:true});
await fs.mkdir(path.join(tmp,'output'),{recursive:true});
const skill='C:/Users/simho/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const py='C:/Users/simho/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const {finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')));
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={navy:'#183447',teal:'#087E83',ink:'#223B49',muted:'#52666F',light:'#F4F7F6',white:'#FFFFFF',line:'#D6E1E1'};
const F='Arial';
function text(s,t,x,y,w,h,size=28,color=C.ink,bold=false){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:F,fontSize:size,color,bold,autoFit:'none',verticalAlignment:'top'};return a;}
function slide(title,notes,sub=''){const s=p.slides.add();s.background.fill=C.white;text(s,title,64,46,1152,82,44,C.navy,true);if(sub)text(s,sub,66,132,1148,52,25,C.muted);text(s,String(p.slides.items.length).padStart(2,'0'),1163,666,50,25,18,C.muted);s.speakerNotes.textFrame.setText((title.startsWith('Appendix')?'Q&A appendix. Outside the timed 5-minute core presentation.\n':'')+notes+'\n\nPresenter: ____________________\nStatus date: 25 September 2026. Blank result fields are intentionally incomplete.');return s;}
function paras(s,items,x=66,y=200,w=1148,step=110){items.forEach((v,i)=>{text(s,v[0],x,y+i*step,w,37,29,C.teal,true);text(s,v[1],x,y+42+i*step,w,65,26,C.ink);});}
function table(s,values,widths,y=194,h=395,size=23){const t=s.tables.add({rows:values.length,columns:values[0].length,left:66,top:y,width:1148,height:h,columnWidths:widths,values});t.borders.assign({style:'solid',fill:C.line,width:1});t.cells.block({row:0,column:0,rowCount:values.length,columnCount:values[0].length}).assign({textStyle:{typeface:F,fontSize:size,color:C.ink},margins:{left:14,right:14,top:10,bottom:9},anchor:'center'});for(let r=0;r<values.length;r++)for(let c=0;c<values[0].length;c++){t.getCell(r,c).fill=r===0?C.navy:(r%2?C.white:C.light);if(r===0)t.getCell(r,c).text.style={typeface:F,fontSize:size,bold:true,color:C.white};}return t;}
async function img(s,file,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(path.join(root,file))),contentType:'image/png',alt:'Project CAD render: '+file,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
const outline='Primary source: ../SG_GoAssist_Prototype_Action_Plan.pdf';
const sensorSources='Sensor specification: STMicroelectronics VL53L0X product page https://www.st.com/en/imaging-and-photonics-solutions/vl53l0x.html and DS11555 Rev 6 https://www.st.com/resource/en/datasheet/vl53l0x.pdf (pp. 1, 21–24). Single-zone ranging gives one distance per reading over I2C. The 940 nm emitter is infrared. Up to 2 m is a conditional manufacturer specification, not verified prototype range. One reading cannot prove the full ramp area clear. Visible RYS1230 marking lasers are separate from the ToF sensor.';
const guide='Official guideline: ../SGBTGC 2026 - IHL Updates 18 Aug 2026.pdf, pp. 16–18 (18 August 2026 update).';
const timed=(seconds,script,sources)=>`${guide}\n5-minute core presentation. Planned speaking time: ${seconds} seconds.\nPresenter cue: ${script}\n${sources}`;
{
const s=p.slides.add();s.background.fill=C.navy;text(s,'SG GoAssist',66,65,1140,92,70,C.white,true);text(s,'Autonomous Passenger Assistance System',69,178,1135,58,33,C.white);text(s,'National University of Singapore (NUS)',69,265,1135,45,29,'#8ED4D0');text(s,'Team: SmaRHt Buses',69,327,1135,43,27,C.white);text(s,'Jin Donghua, Liu Xuan Tong, Ryan Koh Jun Hao,',69,459,1135,40,26,C.white);text(s,'Sim Hong Meng, Zeph Tang Zhenkai',69,504,1135,40,26,C.white);text(s,'Staff-in-charge: Koenraad Mouthaan',69,570,1135,40,24,C.white);text(s,'Draft progress as of 25 September 2026',69,625,1135,34,23,'#BBD0D7');s.speakerNotes.textFrame.setText(timed(15,'Introduce SG GoAssist from NUS team SmaRHt Buses. Members: Jin Donghua, Liu Xuan Tong, Ryan Koh Jun Hao, Sim Hong Meng and Zeph Tang Zhenkai. Staff-in-charge: Koenraad Mouthaan.',outline+', p. 1. Institution and team metadata confirmed by the user.\nCore slides 1–8 total 300 seconds. All following slides are Q&A appendices, outside the timed presentation. A separate video of up to 5 minutes is allowed and remains to be produced. Presenter: ____________________'));}
{
const s=slide('Problem and project objective',timed(30,'Explain that requests must lead to understandable, verified assistance. Include passengers who ask for extra time or guidance without a visible mobility aid. State the controlled-prototype boundary.',outline+', pp. 1–3, 13.'),'A controlled prototype for accessible boarding and alighting');paras(s,[['Passenger need','A clear way to request help and understand when boarding or alighting can proceed.'],['Project objective','Complete one repeatable journey from explicit request to acknowledgement, safe assistance and verified completion.'],['Inclusive scope','Ramp assistance, extra time and audio, visual or haptic guidance based on the passenger’s choice.']],66,208,1148,124);}
{
const s=slide('Alternatives and selected method',timed(40,'Compare design tradeoffs, not measured impact. Manual assistance provides an operator baseline. Camera-only triggering cannot establish consent. Explain why explicit intent with perception and deterministic checks is the selected prototype method.',outline+', pp. 2, 5–9, 13. Comparison is the team design rationale, not a completed experimental comparison.'));table(s,[['Approach','Useful feature','Tradeoff / design decision'],['Manual assistance','Human judgement and flexible intervention','Use as the baseline. It requires an operator to coordinate each journey.'],['Camera-only trigger','Observable assistance cues without app input','A cue cannot establish a request or consent. Reject as ramp authority.'],['Explicit request with sensor checks','Passenger control plus verified system response','Selected method. Adds integration and calibration work.']],[290,360,498],187,386,24);text(s,'ML interprets uncertain scenes. Fixed rules and physical sensors retain safety vetoes.',66,609,1135,61,27,C.teal,true);}
{
const s=slide('Integrated system and safety principle',timed(40,'Walk through the four layers. Emphasize that perception supports a confirmed request. The controller repeats safety checks during movement and verifies deployed and stowed positions.',outline+', pp. 3, 9; docs/grand-challenge-integrated-prototype.md, Safety policy; docs/task-requirements-traceability.md. Software logic exists, but physical integration acceptance remains incomplete. VL53L0X threshold calibration, range/status contract adaptation and controller fault tests remain pending. '+sensorSources+''));table(s,[['Layer','Role in the assistance journey'],['App and stop unit','Record request, confirmation and cancellation for the selected bus.'],['Camera and VL53L0X','Report camera cues, single-zone range and sensor health.'],['Backend and operator','Manage the case, expose reasons and apply safety rules.'],['Mock-bus controller','Repeat local interlocks and verify ramp limit-switch state.']],[340,808],180,348,26);text(s,'Confirmed intent + fresh safety inputs + verified position',66,563,1140,49,33,C.teal,true);text(s,'Uncertainty blocks movement. Completion requires a verified stowed ramp.',66,622,1140,43,27);}
{
const s=slide('Original project contributions',timed(40,'Separate reused technologies from the team work. The proposed contribution is the combined intent-to-outcome assistance workflow and its safety/feedback integration. Avoid world-first claims. Judges assess only original elements, so retain implementation and authorship evidence.',guide+' Originality and Creativity carries 30%. '+outline+', pp. 2–3, 9; docs/grand-challenge-integrated-prototype.md; cad/VALIDATION_v2.md. These are scoped project contributions, not a prior-art novelty assessment.'),'Originality claim is limited to the team’s design and integration work');paras(s,[['Intent and assistance workflow','Retain passenger choice across request, confirmation, cancellation, actuation and verified completion.'],['Safety and accessible feedback integration','Connect case decisions, local interlocks, position checks and passenger/operator status in one auditable loop.'],['Centre-door mechanism concept','Develop the door, ramp and boarding-fixture CAD arrangement and operating sequence for the prototype.']],66,204,1148,114);text(s,'Reused foundations: ESP32, ToF sensors, pretrained detection and ArUco methods.',66,620,1135,48,25,C.muted);}
{
const s=slide('Progress supported by current evidence',timed(60,'Distinguish software, CAD and the sensor bench. Software has documented automated tests and fixture/mock operation. The CAD check is discrete packaging evidence. Explain the 27 valid sensor samples and that accuracy is unverified. Explain the selected VL53L0X single-zone field and the remaining calibration, firmware adaptation, physical and ML evidence.', 'Sources: docs/feature-readiness-matrix.md; docs/grand-challenge-integrated-prototype.md; cad/VALIDATION_v2.md; hardware/esp32-s3-tof-test/README.md; artifacts/apas-tof-build/serial-powercycle-test.txt; hardware/edge-observer/ml1/README.md. Image: cad/Punggol_WeRide_Robobus_v2_deployed.png, project CAD render. No full software rerun or physical integration trial performed for this draft. '+sensorSources+''));await img(s,'cad/Punggol_WeRide_Robobus_v2_deployed.png',55,172,588,390);paras(s,[['Software','App, backend and operator flow with mock test evidence.'],['CAD','73 sampled poses. Zero moving-part intersections in a discrete check.'],['Sensor bench','27 consecutive valid VL53L0X samples, 30–136 mm after power cycle.']],685,175,525,124);text(s,'Physical integration and measured ML performance remain incomplete.',66,591,1135,44,28,C.teal,true);text(s,'VL53L0X covers a limited field. Accuracy and physical ramp coverage remain unverified.',66,642,1135,41,23,C.muted);}
{
const s=slide('Validation plan and results',timed(40,'State these are planned targets. Blank fields await measured results. Compare the same journey with manual assistance and collect consented feedback. Explain that physical trials must demonstrate both successful assistance and safe failure responses.',outline+', pp. 12–13. Original targets shown. Later docs/task-requirements-traceability.md adds 30 requests per explicit source and acknowledgement P95 under 2 seconds. Confirm the final protocol. Results intentionally blank.'));table(s,[['Test','Original target','Result'],['Request','20/20 delivery trials, acknowledgement within 2 s',''],['Assistance cue','At least 90% wheelchair/PMA recall, at least 10 FPS',''],['Safety and actuation','Zero missed obstructions. 50 cycles without binding',''],['Docking and journey','10 docking trials. At least 9/10 cold-start journeys',''],['Dwell','No premature CLEAR in defined tests','']],[260,680,208],183,395,23);text(s,'Impact and accessibility findings:',66,609,620,36,25,C.teal,true);text(s,'____________________________________________',66,652,1120,33,24,C.muted);}
{
const s=slide('Remaining work and competition milestones',timed(35,'Close with the next milestone: a repeatable physical journey supported by measured evidence. State official dates carefully. The report and poster are due in September, while slideshow/video submission is in October. The organiser labels dates tentative.',guide+' pp. 16–17. Action-plan 27 September content freeze is an internal planning target, not an organiser deadline. Main event permits 5-minute presentation, up to 5-minute video and 5-minute Q&A. Separate video remains incomplete.'));text(s,'Next: calibrate VL53L0X, adapt controller thresholds and fault logic, then test.',66,158,1135,79,30,C.teal,true);table(s,[['Official milestone','Date'],['Project report and display-poster artwork','30 September 2026'],['Pre-event prototype showcase (25 minutes)','7 October 2026'],['Main-event slideshow and video submission','15 October 2026'],['Main event: presentation, video and Q&A','24 October 2026']],[825,323],256,296,25);text(s,'Dates are tentative. Main-event format: 5 min talk, up to 5 min video, 5 min Q&A.',66,587,1140,67,25,C.muted);text(s,'Core presentation ends here. Supporting slides follow for Q&A.',66,654,1140,33,23,C.teal,true);}

{
const s=slide('Appendix A. Intended journey',outline+', p. 3. The original nine steps are request, recognise, prepare, dock, mark zone, check zone, deploy, board and complete. Current physical end-to-end completion has not been established. The camera interprets the scene and VL53L0X provides a single-zone range check in a limited monitored field. One range does not establish full-area clearance. '+sensorSources+'');table(s,[['Stage','Passenger or system action','Required outcome'],['1  Request and recognise','Select assistance and bus. Perception adds cues.','Explicit intent remains authoritative.'],['2  Prepare and dock','Reserve dwell and align with the boarding fixture.','Correct bus, stop and ramp reach.'],['3  Mark and check','Mark area. Check camera and VL53L0X inputs.','Clear, fresh safety inputs.'],['4  Deploy and board','Open door, deploy ramp and maintain dwell.','Verify deployed position and monitor interlocks.'],['5  Complete','Retract, verify stowed and close the door.','Save outcome or escalate a fault.']],[240,454,454],173,444,23);text(s,'Second demonstration scenario: extra time and guidance without a ramp request.',66,635,1128,40,24,C.teal,true);}
{
const s=slide('Appendix B. Architecture and authority',outline+', pp. 5, 9; docs/grand-challenge-integrated-prototype.md, Safety policy and Portable build; docs/task-requirements-traceability.md, SR-01–04.','Shared messages connect software, sensing and the mock bus');table(s,[['Layer','Main components','Responsibility'],['Passenger','App, tactile stop unit, optional NFC','Record request, confirmation and cancellation.'],['Perception','Camera, edge observer, VL53L0X','Publish camera cues, one range and sensor health.'],['Decision','Backend case state machine, operator console','Match the case and apply deterministic safety gates.'],['Vehicle','ESP32 controller, ramp/door, limit switches','Repeat local interlocks and verify motion outcome.']],[195,431,522],201,342,24);text(s,'Only passenger or operator confirmation establishes ramp intent.',66,574,1135,38,29,C.teal,true);text(s,'ML supports decisions. It cannot override a safety interlock.',66,622,1135,36,26,C.ink);}
{
const s=slide('Appendix C. Software evidence','Sources: README.md, Integrated assistance demonstrator and Private hybrid assistant; docs/grand-challenge-integrated-prototype.md; docs/feature-readiness-matrix.md. No assertion that all tests were rerun for this report.','The repository implements the competition software loop');paras(s,[['Passenger and operator interfaces','Request assistance, track case status, cancel and expose reasons for blocked or escalated actions.'],['Backend and mock control','Persist cases and audit events. Reject duplicate actions and verify deployed/stowed telemetry.'],['Verification still required','Physical actuation and on-device ARM64 Qwen tests. Transport arrivals and selected amenities use labelled fixtures.']],66,201,1148,124);}
{
const s=slide('Appendix D. VL53L0X capability and evidence','Sources: hardware/esp32-s3-tof-test/README.md, Verification on 23 September 2026; artifacts/apas-tof-build/serial-powercycle-test.txt. Measurements are sensor-reported values without a known-distance accuracy comparison. '+sensorSources+' Controller adaptation and threshold/fault tests remain pending. Invalid or stale readings must block movement. Visible marking lasers do not measure range.','ESP32-S3 and VL53L0X live ranging verified on 23 September');text(s,'27 consecutive valid samples',66,201,1135,60,44,C.teal,true);text(s,'30–136 mm after a full sensor power cycle',66,276,1135,47,30);paras(s,[['Selected sensor capability','One distance per reading over I²C. 940 nm infrared. Up to 2 m under specified conditions.'],['Coverage limits','No depth map or object classification. One reading cannot clear the whole ramp area.']],66,358,1148,116);text(s,'Calibration and firmware tests pending. Visible RYS1230 marking lasers are separate.',66,623,1135,56,24,C.muted);}

{
const s=slide('Appendix E. Machine-learning evidence',outline+', pp. 5–8; hardware/edge-observer/README.md; hardware/edge-observer/ml1/README.md; hardware/edge-observer/ml1/LABEL_GUIDE.md. Dataset scope differs: original outline 300–500 ML1 images, later README 800–1,200. Team should confirm controlled-demo scope before capture. No measured trained-model evidence located in reviewed materials. Selected ML2 method: camera scene interpretation with VL53L0X single-zone checks in a limited monitored field. A single range cannot establish full-ramp coverage or replace object classification. '+sensorSources+'');table(s,[['Module','Intended decision','Current evidence / next evidence'],['ML1  Assistance cue','Recognise selected observable aids.','Scripts and label guide ready. Add trained weights, held-out metrics and device latency.'],['ML2  Ramp zone','Camera scene cues with limited range checks.','Add camera evaluation and single-zone range tests. Full-area clearance remains unverified.'],['ML3  Dwell state','Classify active, clear or uncertain boarding.','Training/evaluation evidence pending. Validate the fixed-dwell sensor-clear fallback.']],[225,345,578],187,359,24);text(s,'A detection never diagnoses disability or authorizes ramp movement by itself.',66,580,1135,73,29,C.teal,true);}
{
const s=slide('Appendix F. Original deliverables D1–D5',outline+', p. 12. Status derives from reviewed repository evidence as of 25 September 2026. D1/D3 software availability does not establish completed hardware acceptance.','Status against the original action plan');table(s,[['ID and owner','Deliverable','Progress / missing acceptance'],['D1  CE1','Architecture, interfaces and states','Documented. Final group review pending.'],['D2  EE1 / EE2 / ME1','Integrated mock bus, stop and fixture','Subsystem evidence exists. Cold-start physical trials pending.'],['D3  CE1','Passenger app and dashboard','Implemented in software. Final demonstration evidence pending.'],['D4  CE2 / EE1','ML1 package','Training workflow ready. Weights, metrics and model card pending.'],['D5  CE2 / EE1 / ME1','ML2 and safety-fusion package','Adapt VL53L0X range and fault logic. Measured perception and safety results pending.']],[239,374,535],192,438,23);}
{
const s=slide('Appendix G. Original deliverables D6–D9',outline+', p. 12; cad/VALIDATION_v2.md; hardware/INTEGRATED_PROTOTYPE.md. The draft report and this deck contribute to D9, but submission acceptance is not established.','Role labels follow the outline. Assign the confirmed members to roles.');table(s,[['ID and owner','Deliverable','Progress / missing acceptance'],['D6  CE2 / CE1 / EE2','ML3 or documented fallback','Trained classifier evidence pending. Validate fallback and no-premature-CLEAR cases.'],['D7  EE2 / ME1','Mechanical and electrical package','CAD and circuit material available. Final BOM, power and cycle results pending.'],['D8  All / ME1','Validation and accessibility report','Protocol available. Physical metrics, baseline and user findings incomplete.'],['D9  All / CE1','Competition submission pack','Report and presentation drafts. Video, final evidence and packaging pending.']],[239,374,535],207,379,23);}
{
const s=slide('Appendix H. User feedback and impact',outline+', p. 13. Obtain consent before any participant study. If participants are classmates only, describe scenario testing rather than validation by disabled users. Compare the same scripted journey under manual assistance and GoAssist. Blank fields intentionally await actual evidence.','Study findings remain incomplete');table(s,[['Study field','Evidence to add'],['Participants, consent and test date',''],['Clarity and control',''],['Confidence and comfort',''],['Manual baseline versus GoAssist',''],['Design changes from feedback','']],[421,727],200,379,24);text(s,'Baseline measures: acknowledgement, manual interventions, completion and waiting time.',66,619,1135,57,24,C.muted);}
{
const s=slide('Appendix I. Costs and final evidence',outline+', pp. 12, 14. Cost fields and final evidence links intentionally blank. These are editable working fields, not zero costs or completed submissions.','Complete these fields after hardware and evidence review');table(s,[['Budget / evidence item','Confirmed value or file link'],['Total component cost (SGD)',''],['Final BOM and power budget',''],['Physical integration photos and cycle logs',''],['Model metrics and model cards',''],['Demo video and final source archive','']],[549,599],196,418,24);}
const candidate=path.join(tmp,'candidate.pptx');
await (await PresentationFile.exportPptx(p)).save(candidate);
await fs.writeFile(path.join(tmp,'presentation.json'),JSON.stringify(p.toProto()));
console.log('Exported candidate with '+p.slides.items.length+' slides');
const result=await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:path.join(tmp,'output/validated.pptx'),pythonExecutable:py,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[3,4,7,8,9,10,13,14,15,16,17].flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:17,requiredNativeTableOwnerSlides:[3,4,7,8,9,10,13,14,15,16,17],fontPolicy:{basis:'design',families:[F]},verifyArtifactToolImport:true,receiptPath:path.join(tmp,'validation.json')});
console.log(JSON.stringify(result));
const final=await PresentationFile.importPptx(await FileBlob.load(path.join(tmp,'output/validated.pptx')));
for(let i=0;i<final.slides.items.length;i++){const s=final.slides.items[i];const out=await final.export({slide:s,format:'png',scale:1});await fs.writeFile(path.join(tmp,'slide-'+String(i+1).padStart(2,'0')+'.png'),new Uint8Array(await out.arrayBuffer()));console.log('Rendered '+(i+1));}
// After visual review, copy tmp/output/validated.pptx to the requested editable
// deliverable at output/project-draft/NUS - SmaRHt Buses - Project Presentation Draft.pptx.
// Preserve the previous deliverable under artifacts/project-draft/slides/superseded.


